export const AGENT_TYPES = {
  NEW_AGENT: 'New Agent',
  POSP: 'POSP',
  COMPOSITE: 'Composite',
  TRANSFER: 'Transfer'
} as const;

export const AGENT_NAMES = [
  'Rahul Sharma',
  'Amit Patel',
  'Rohit Kumar',
  'Akash Singh',
  'Priya Sharma',
  'Neha Patel',
  'Sneha Joshi',
  'Pooja Verma',
  'Rohan Mehta',
  'Karan Shah',
  'Ankit Gupta',
  'Vikas Yadav',
  'Suresh Kumar',
  'Rajesh Sharma',
  'Ajay Singh',
  'Vijay Patel',
  'Nikhil Joshi',
  'Manish Gupta',
  'Sameer Khan',
  'Arjun Mehta',
  'Aditya Shah',
  'Varun Kapoor',
  'Siddharth Jain',
  'Abhishek Verma',
  'Mohit Agarwal',
  'Sumit Mishra',
  'Deepak Kumar',
  'Naveen Singh',
  'Sachin Patil',
  'Prakash Joshi',
  'Ganesh Pawar',
  'Santosh Shinde',
  'Mahesh Patil',
  'Sunil More',
  'Nitin Jadhav',
  'Akshay Kulkarni',
  'Tejas Deshmukh',
  'Omkar Patil',
  'Sagar Pawar',
  'Chetan Shinde',
  'Snehal Patil',
  'Pankaj Sharma',
  'Ravi Verma',
  'Raj Malhotra',
  'Varun Sharma',
  'Harsh Patel',
  'Yash Mehta',
  'Dhruv Shah',
  'Dev Joshi',
  'Ayush Gupta',
  'Anjali Sharma',
  'Kavita Patel',
  'Riya Mehta',
  'Simran Kaur',
  'Nisha Verma',
  'Aarti Joshi',
  'Shweta Gupta',
  'Divya Singh',
  'Tanya Shah',
  'Muskan Khan',
  'Komal Sharma',
  'Payal Patel',
  'Sonali Mehta',
  'Swati Verma',
  'Poonam Gupta',
  'Megha Joshi',
  'Isha Shah',
  'Shruti Jain',
  'Ananya Mehta',
  'Sakshi Patil',
  'Rahul Patil',
  'Amit Shah',
  'Rohit Deshmukh',
  'Kunal Joshi',
  'Tushar Patil',
  'Pranav Mehta',
  'Atharva Kulkarni',
  'Ritesh Sharma',
  'Sameer Patil',
  'Vivek Shah',
  'Abhishek Patil',
  'Mayur Joshi',
  'Mandar Kulkarni',
  'Shubham Verma',
  'Akhil Sharma',
  'Harshad Patil',
  'Rajiv Mehta',
  'Sanjay Shah',
  'Dinesh Kumar',
  'Ashish Gupta',
  'Tarun Singh',
  'Gaurav Sharma',
  'Varsha Patel',
  'Neelam Joshi',
  'Priti Shah',
  'Madhuri Patil',
  'Radhika Mehta',
  'Monika Sharma',
  'Kiran Verma',
  'Reema Gupta'
] as const;

export const SELECTOR_LABELS = {
  salutation: 'Salutation',
  gender: 'Gender',
  relation: 'Relation',
  addressSameApplicant: 'Address Same Applicant'
} as const;

export const UI_LABELS = {
  onBoardAgent: 'Onboard Agent',
  submit: 'Submit',
  verifyOtp: 'Verify OTP',
  searchTable: 'Search Table'
} as const;
